name: Update Clock Image

on:
  schedule:
    - cron: '*/10 * * * *'  # 10分ごとに実行
  workflow_dispatch:        # 手動実行もOK！

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ImageMagick
        run: sudo apt-get install -y imagemagick

      - name: Run clock script
        run: bash 0.sh

      - name: Show files
        run: ls -l

      - name: Commit and Push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add clock.png || echo "No image to add"
          git commit -m "Update clock image" || echo "No changes to commit"
          git push --force https://x-access-token:${TOKEN}@github.com/code-jpn/clock.git


